language: php
php: 
 - 5.3
services:
 - memcached
before_script: 
 - sudo apt-get install memcached
 - echo -e 'extension = "apc.so" \n extension = "memcache.so" \n extension = "memcached.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
